"""Export the trained machine and sample cards for the static web demo.

Writes web/weights.js and web/samples.js so the demo in web/ runs fully
client-side (file://, any static host, GitHub Pages).

Run:  python -m mnist_mech.export_web
"""

import json

import numpy as np

from .data import binarize, load_mnist

SAMPLES_PER_DIGIT = 3


def _card_to_hex(card):
    """Pack a (28, 28) binary card into a 196-char hex string, row-major."""
    bits = card.reshape(-1)
    nibbles = bits.reshape(196, 4)
    values = nibbles @ np.array([8, 4, 2, 1])
    return "".join(format(v, "x") for v in values)


def export(weights_path="weights/weights.json", data_dir="data",
           out_dir="web"):
    with open(weights_path) as f:
        spec = json.load(f)

    with open(f"{out_dir}/weights.js", "w") as f:
        f.write("// generated by python -m mnist_mech.export_web\n")
        f.write("const MACHINE = ")
        json.dump({
            "weights": spec["weights"],
            "bias": spec["bias"],
            "testAccuracy": spec["quantized_test_accuracy"],
            "nonzeroWeights": spec["nonzero_weights"],
        }, f)
        f.write(";\n")

    _, _, test_images, test_labels = load_mnist(data_dir)
    cards = binarize(test_images)
    samples = []
    for digit in range(10):
        indices = np.flatnonzero(test_labels == digit)[:SAMPLES_PER_DIGIT]
        for i in indices:
            samples.append({"label": int(digit),
                            "index": int(i),
                            "bits": _card_to_hex(cards[i])})

    with open(f"{out_dir}/samples.js", "w") as f:
        f.write("// generated by python -m mnist_mech.export_web\n")
        f.write("const SAMPLES = ")
        json.dump(samples, f)
        f.write(";\n")

    print(f"wrote {out_dir}/weights.js and {out_dir}/samples.js "
          f"({len(samples)} sample cards)")


if __name__ == "__main__":
    export()
